sudo: required
services:
    - docker

before_install:
    - docker build -t capstring/multi-container-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true capstring/multi-container-test npm test

after_success:
    - docker build -t capstring/multi-client ./client
    - docker build -t capstring/multi-nginx ./nginx
    - docker build -t capstring/multi-server ./server
    - docker build -t capstring/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push capstring/multi-client
    - docker push capstring/multi-nginx
    - docker push capstring/multi-server
    - docker push capstring/multi-worker