sudo: required
services:
    - docker

before_install:
    - docker build -t capstring/multi-container-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true capstring/multi-container-test npm test

after_success:
    - docker build -t capstring/multi-client ./client
    - docker build -t capstring/multi-nginx ./nginx
    - docker build -t capstring/multi-server ./server
    - docker build -t capstring/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push capstring/multi-client
    - docker push capstring/multi-nginx
    - docker push capstring/multi-server
    - docker push capstring/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-eu-central-1-058575022549
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY